### ISSUE TITLE
More message events

### ISSUE THREAD

**Issue by KayaGG** [GoobyMain/Gooby.AutoMessage#1]
It would be cool if messages could be send after executions/titan executions/etc instead of just at game start, half time, and game end. Not an issue just a feature request.

**Comment by GoobyMain** [comment]
> It would be cool if messages could be send after executions/titan executions/etc instead of just at game start, half time, and game end. Not an issue just a feature request.

That would be cool! I'll implement that while I'm working on fixing a couple issues, it should be really quick. Let me know if you have any good ideas for other events you might want to send a message during

**Comment by KayaGG** [comment]
I'll let you know if I think of any

**Comment by GoobyMain** [comment]
It would be really cool to write more events but I'm sick of having this mod unfinished and just want to call it done, lol
If you want to implement it yourself send a pull request!
